#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the acmTeam function below.
def acmTeam(topic):
    res=[0,0]
    for i in range(len(topic)-1):
        for j in range(i+1,len(topic)):
            count=str(int(topic[i]) + int(topic[j])).count('1')+\
            str(int(topic[i]) + int(topic[j])).count('2')
            if count>res[0]:
                res[0]=count
                res[1]=1
            elif res[0]==count:
                res[1]+=1
    return res

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    topic = []

    for _ in range(n):
        topic_item = input()
        topic.append(topic_item)

    result = acmTeam(topic)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
