#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the cutTheSticks function below.
def cutTheSticks(arr):
    test={i:arr.count(i) for i in sorted(arr)}
    ite=[*test.values()][:-1]
    output=[len(arr)]
    length=len(arr)
    for i in ite:
        output.append(length-i)
        length=length-i
    return output

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    result = cutTheSticks(arr)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
